[package]
name = "escrow-program"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = "1.5.7"
solana-program = "3.0.0"
thiserror = "2.0.16"
spl-token = { version = "4.0.1", features = ["no-entrypoint"] }
arrayref = "0.3.7"

[lib]
crate-type = ["cdylib", "lib"]
